### ISSUE TITLE
Crash if included html that extends from other html 

### ISSUE THREAD

**Issue by LuisReyes98** [jazzdotdev/flute#140]
# Issue
The theme loader will crash if it is included a component 
`{% include "component.html" %} `
and that component is extending from something else 
`{% extends "component-2.html" %}`

## Recreating the error 
trying to run the theme [multi-component-example](https://github.com/LuisReyes98/multi-component-example) thats has as parents [component-holder](https://github.com/LuisReyes98/component-holder) and [component-sitter](https://github.com/LuisReyes98/component-sitter)  will cause the it to crash

**Comment by naturallymitchell** [comment]
why doesn't `multi-component-example` inherit from `base-theme`?

**Comment by LuisReyes98** [comment]
Because I wanted to have the least amount of themes to recreate the error

**Comment by Arnaz87** [comment]
Does including usually works? The theme rewriter does not mind the content of the files so I don't think the issue is there. What's the error message of the crash?

**Comment by naturallymitchell** [comment]
there's no message, I believe, since torchbear panics.  see https://github.com/foundpatterns/torchbear/issues/214#issuecomment-454640897

**Comment by naturallymitchell** [comment]
"The theme loader will crash"....?
meaning, the tera bindings..  that could go with what Keats told us in https://github.com/foundpatterns/torchbear/issues/128

**Comment by Arnaz87** [comment]
It would've be nice if you had made a lighttouch branch with the themes, so one can just clone it and run it

**Comment by Arnaz87** [comment]
I can include the holder if that holder does not extends the parent

**Comment by Arnaz87** [comment]
I can also `{% include "^/component-holder.html" %}` so it definitely is not a template rewriter error, this is a tera bug.

**Comment by naturallymitchell** [comment]
@Arnaz87 @LuisReyes98 what exactly is the change we need to make now?

something like, "add support for X in Y"..

https://github.com/foundpatterns/torchbear/issues/214#issuecomment-457041607

**Comment by Arnaz87** [comment]
Error report, using tera 1.0 alpha
https://pastebin.com/0KyN7kyw

**Comment by Arnaz87** [comment]
Clone this branch of lighttouch
https://github.com/foundpatterns/lighttouch/tree/multi-component-example

**Comment by Arnaz87** [comment]
This error is most likely a Tera error, we need a pure rust-tera example of it, so that either Keats or us can fix it.

**Comment by Arnaz87** [comment]
the line the report links to
https://github.com/Keats/tera/blob/3707c9cbf4ad69e37f2995f6e909c204425f4567/src/renderer/processor.rs#L808

**Comment by Arnaz87** [comment]
Pure rust example of the error
https://github.com/Arnaz87/tera-test

It's error
~~~
thread 'main' panicked at 'internal error: entered unreachable code: render_node -> unexpected node: Extends(WS { left: false, right: false }, "parent-holder.txt")', /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/processor.rs:812:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: tera::renderer::processor::Processor::render_node
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/processor.rs:812
   8: tera::renderer::processor::Processor::render_body
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/processor.rs:150
   9: tera::renderer::processor::Processor::render_node
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/processor.rs:804
  10: tera::renderer::processor::Processor::render
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/processor.rs:858
  11: tera::renderer::Renderer::render
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/renderer/mod.rs:54
  12: tera::tera::Tera::render
             at /home/arnaud/.cargo/git/checkouts/tera-ae1ac1f255426cfc/68dfeb5/src/tera.rs:309
  13: tera_test::main
             at src/main.rs:7
  14: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  18: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  19: main
  20: __libc_start_main
  21: _start
~~~

**Comment by Arnaz87** [comment]
https://github.com/Keats/tera/issues/385

**Comment by naturallymitchell** [comment]
fixed upstream in foundpatterns/tera master
